version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  chat:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/myapp